[package]
name = "quikka"
version = "0.1.0"
authors = ["ButterBridge <jonnyrathbone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
tuple-map = "0.4.0"